config/routes.rb
Rails.application.routes.draw do
  resources :photos

  resources :categories
  resources :products

  devise_for :admins
  devise_for :users

  root 'products#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_products
  has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  dragonfly_accessor :image
  
  has_many :product_photos
  has_many :products, through: :product_photos
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :category_products
  has_many :categories, through: :category_products
  has_many :product_photos
  has_many :photos, through: :product_photos
end

app/models/product_photo.rb
class ProductPhoto < ActiveRecord::Base
  belongs_to :product
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_categories
  
  private
  
  def set_categories
    @categories = Category.order(:rank)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :image_url, :rank, :active)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @photos = Photo.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @photos = Photo.all
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @photos = Photo.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_list_menu.erb
<% @categories.each do |category| %>
  <li><a href="categories/<%= category.id %>"><%= category.name %></a></li>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Rank</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.image_url %></td>
        <td><%= category.rank %></td>
        <td><%= category.active %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

  <!-- Side Bar -->
 
        <div class="large-3 small-12 columns">
 
          <div class="nate container">
            <div class="nate ear left"><div class="nate ear inner"> </div> </div>
            <div class="nate ear right"><div class="nate ear inner"> </div> </div>

            <div class="nate tongue"> </div>

            <div class="nate lower-face">
              <div class="nate nose">
              </div>
              <div class="nate mouth"> </div> 
            </div>
            <div class="nate head"> </div>
            <div class="nate eye left"><div class="nate brow left"></div><div class="nate pupil"><div class="nate pupil reflection" > </div> </div> </div>
            <div class="nate eye right"><div class="nate brow right"></div><div class="nate pupil"><div class="nate pupil reflection" > </div>  </div> </div>
          </div>     
 
          <div class="hide-for-small panel">
            <h3><%= @category.name %></h3>
            <h5 class="subheader"><%= @category.description %></h5>
          </div>
 
          <a href="#">
          <div class="panel callout radius">
            <h6>99&nbsp; items in your cart</h6>
          </div>
          </a>
 
        </div>
 
    <!-- End Side Bar -->
 
 
    <!-- Thumbnails -->
 
        <div class="large-9 columns">
          <div class="row" data-equalizer>
          <% @category.products.each do |product| %>
            <%= link_to product do %>
            <div class="large-3 small-6 columns product image" data-equalizer-watch>
              <%= image_tag product.photos.first.image.thumb('150x').url if product.photos.first.image_stored? %>
              <div class="panel product name">
                <h5><%= product.name %></h5>
                <h6 class="subheader product price">$<%= product.price.round(2) %></h6>
              </div>
              <ul class="horizontal product admin">
                <li><%= link_to 'Edit', edit_product_path(product) %></li>
                <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
            <% end %>
          <% end %>
 
    <!-- End Thumbnails -->
          </div>
        </div>
      </div>
 
 
    <!-- Footer -->
 
      <footer class="row">
        <div class="large-12 columns"><hr />
          <div class="row">
 
            <div class="large-4 columns">
              <p>Copyright &copy; <%= Time.now.year %> - Ryan Spencer</p>
            </div>
 
            <div class="large-8 columns">
              <ul class="inline-list right">
                <%= render "categories/list_menu" %>
              </ul>
            </div>
 
          </div>
        </div>
      </footer>
 
    <!-- End Footer -->
 
    </div>
  </div>    

app/views/layouts/_header.html.erb
<!-- Navigation --> 
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1>
        <a href="#">
          Air Guitar Emporium
        </a>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Home",       '/' %></li>
      <li class="divider"></li>
      <li><%= link_to "Categories", '/categories' %> </li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="#">User</a>
        <ul class="dropdown">
          <% if user_signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
              </li>
            </ul>
          </li>
          <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Create Account", "devise/registrations/new" %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </section>
</nav>
<!-- End Top Bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="section">
    <div class="sub-header"><ul class="inline-list right"><%= render "categories/list_menu" %></ul></div>
  </div>
  <div class="row">
    <%= yield %>
  </div>
  </div>
</body>
</html>

app/views/photos/_form.html.erb
<div class="large-12">
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.file_field :image %>
    <%= f.submit "Upload Photo", class: "button tiny" %>
  </div>
<% end %>
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<%= link_to 'New Photo', new_photo_path, class: "button small" %>
<div class="large-12" data-equalizer>
  <% @photos.each do |photo| %>
  <div class="large-3 column left" data-equalizer-watch>
    <%= image_tag photo.image.thumb('160x').url %>
    <ul class="horizontal">
      <li><%= link_to 'View', photo, class: "button tiny" %></li>
      <li><%= link_to 'Delete', photo, class: "button tiny alert", method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to '<< Show All', photos_path %><br>
<%= image_tag @photo.image.thumb('300x').url if @photo.image_stored? %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_field :image_link %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <select name="photo">
      <% @photos.each do |photo| %>
      <option value="<%= photo.id %>"><%= photo.image_uid %></option>
       <% end %>
    </select>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="large-12 columns">
<% @products.each do |product| %>
<div class="large-3 columns product item">
  <%= link_to product do %>
  <%= image_tag product.photos.first.image.thumb('150x').url if product.photos.first.image_stored? %>
  <div class="product name"><%= product.name %></div>
  <% end %>
  <div class="product price"><%= product.price.round(2) %></div>
  <ul class="horizontal product admin">
    <li><%= link_to 'Edit', edit_product_path(product) %></li>
    <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</div>
<% end %>
</div>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <%= image_tag @product.photos.first.image.thumb('300x').url if @product.photos.first.image_stored? %>
</p>